### ISSUE TITLE
Duplicates drop items sometimes when climbing stairs

### ISSUE THREAD

**Issue by hamiguazzz** [faqy003/OniMod-Stairs#2] opened 2020-05-06 17:14 UTC
**If duplicates climb stairs carrying something, they may drop it down.** This appears continually when width of stairs' chain small.
![a](https://user-images.githubusercontent.com/36464835/81205522-66a7eb00-8ffd-11ea-857f-31c34b8a75f3.png)

The most confusing thing is that sometimes after dropping the item, the duplicate can carry it again, which actually lies in unreachable distance.
![b](https://user-images.githubusercontent.com/36464835/81206920-5f81dc80-8fff-11ea-968d-6c23e58eaba6.png)

These too bugs maybe refer to a same place, but I cannot help to fix it. And these bugs lead to terrible experience, especially when facing to the **endless loop of trying carrying <-> dropping**. 

I like this mod and looking forward to the fix.

**Comment by hamiguazzz** [comment] 2020-05-06 17:16
To avoid conflict, enabled mod list is below:
This mod
Asphalt Stairs
Asphalt Tiles
Mod Manager // by @Ony

**Comment by fleeting-aardvark** [comment] 2020-11-24 02:46
I can confirm this pathing / dropping issue.  It happens on longer runs of stairs for me.  It gets quite irritating when a dupe keeps dropping and then picking up something similar, just to drop it and pick up the something else.  The duplicants act like they have lost their mind.
I do not use the mods "Asphalt Stairs" or "Asphalt Tiles".

**Comment by SoraHjort** [comment] 2021-01-31 02:07
I run into this issue when they use the stairs wrong. They'll approach from behind and then do a ledge climb. And when they've done the climb, that's when they'll drop the items.

https://i.imgur.com/I7d07aM.png

I also ran into an issue where they were dropping items when they got to the top of a long staircase, with the top being covered in scaffolding. Which was cause they climbed onto the scaffolding because they wanted to go the other direction than the stairs would have exited on top.

**Comment by faqy003** [comment] 2022-06-12 15:18
This already fixed in 2.0 version. 
If you still have issue , please open another one.

**Closed** 2022-06-12 15:18 UTC
Labels: bug
